on:
  [pull_request]

name: Jira Check

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:
      - name: logger
        uses: hmarr/debug-action
      - name: Checkout
        uses: actions/checkout@master
      - name: Set output
        id: vars2
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
      - name: Get Branch Name
        id: vars
        run: echo "$ID"
        env:
          ID: $(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")   
      - name : Testing pull request name
        run: echo ${{ github.env.payload.pull_request.title }}
      
      - name : Testing pull request name1
        run: echo ${{ fromJson(${}) }}
        
      - name : Testing pull request name3
        run: echo ${{ github.env.payload }}
        
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Get Issue Key
        id: find
        uses: atlassian/gajira-find-issue-key@v2.0.1
        with:
          from:  branch
          string: "echo ${{ steps.vars.outputs.short_ref }}"

      - name: Find issue info
        run: echo "Issue ${{ steps.find.outputs.issue }} was found"
