on:
  [pull_request]

name: Jira Check

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get PR Name
        id: vars
        run: echo "$PR_NAME"
        env:
          PR_NAME: ${{github.event.pull_request.title}}
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: test_print
        run: echo "$PR_NAME"
      - name: Get Issue Key
        id: find
        uses: atlassian/gajira-find-issue-key@v2.0.1
        with:
          from:  branch
          string: "${PR_NAME}"

      - name: Find issue info
        run: echo "Issue ${{ steps.find.outputs.issue }} was found"
